### PR TITLE
Update featured builds

### PR DESCRIPTION
**Pull request by Pabl0cks**
We could update our featured builds to showoff more recent projects using Scaffold ETH-2. In this PR I'm proposing to have as Featured builds:
- hacked wallet recovery. One of the most popular builds, very useful tool to recover assets from hacked wallets.
- address.vision. Already has useful features and active development.
- I think we can leave abi.ninja since is also one of the most popular builds, and we are actively migrating it to SE-2.

I've also added hover effect in all the links that were missing it (builds were one of them), so it's more intuitive for the user what is clickable and what not.

In future iterations we could also add more builds to this section, making it expandable to show more than the 3 featured builds.

### CODE REVIEW

**Comment by Pabl0cks** [comment]
For address.vision Andrea has prepared a new logo for Featured builds:

<details>
  <summary>New logo</summary>
  
build-addressVision2
</details>

have some doubts about whether the logo should match the real product "logo typography" or not. 
As for the emoji in the product logo, I believe it may display a different emoji depending on the operating system you are using. Therefore, we should probably choose the most common one among our users/target audience, I guess Linux or Mac :)

It might be a good idea for the product itself to choose one of the eyes and use a svg/png instead, so it is familiar for all users and doesn't look fishy when they see a different pair of eyes somewhere.

**Comment by carletex** [comment]
Thanks @Pabl0cks !!

I like the new logo, it's smoother (and consistent across OS!). I think we should use for the landing. And maybe change it on address.vision if @portdeveloper likes it.

Another thing: should we just link to the tool instead of the intermediate BG build page (not very pretty... my fault haha)? the wallet recovery doesn't have the "Fork" link on the site, but maybe we could ask them to add it.

Thoughts?

**Comment by Pabl0cks** [comment]
> I like the new logo, it's smoother (and consistent across OS!). I think we should use for the landing. And maybe change it on address.vision if @portdeveloper likes it.

Agree!

> Another thing: should we just link to the tool instead of the intermediate BG build page (not very pretty... my fault haha)? the wallet recovery doesn't have the "Fork" link on the site, but maybe we could ask them to add it.

Yeah maybe right now is better to send to the Live project. If we can manage to get "Fork" to have repo access in wallet recovery would be great !! 
In the future we could either improve the build page in BG, or add a custom build page into buidlguidl.com for the Featured builds.

**Comment by carletex** [comment]
Ok! Let's do it:

- New address vision image
- Link to live project

Thanks Pablo!

**Comment by technophile-04** [comment]
> It might be a good idea for the product itself to choose one of the eyes and use a svg/png instead
> I like the new logo, it's smoother (and consistent across OS!). 

💯💯 !! 

> should we just link to the tool instead of the intermediate BG build page 

yup makes sense 🙌

**Comment by Pabl0cks** [comment]
Just pushed last changes, thanks for the feedback! 🙌♥

**Review by technophile-04 — APPROVED** [review]
Tysm Pablo !!! Looking great !!! 

Just pushed [3a7354e](https://github.com/BuidlGuidl/buidlguidl.com/pull/23/commits/3a7354e553409e9df08a7ce107f9e7d69f3fd860)  to remove todo but it was not related to this PR

**Pull request merged**
